Added DB Models Migration
Nazarii1017/field_booker pull request #1
Opened 2021-11-11 14:43 UTC by Nazarii1017

2021-11-11 14:53 UTC, zakharantoshchenko commented on app/models/user.rb
> +  # Include default devise modules. Others available are:
https://guides.rubyonrails.org/association_basics.html

2021-11-11 14:57 UTC, zakharantoshchenko requested changes

2021-11-11 14:57 UTC, zakharantoshchenko commented on app/models/field.rb
> +class Field < ApplicationRecord
https://guides.rubyonrails.org/association_basics.html

2021-11-11 14:57 UTC, zakharantoshchenko commented on db/schema.rb
> +    t.integer "duration"
что значит это поле ?

2021-11-11 14:57 UTC, zakharantoshchenko commented on db/schema.rb
> +    t.string "field_coverage"
что это за поле?

2021-11-11 14:57 UTC, zakharantoshchenko commented on db/migrate/20211111134104_devise_create_users.rb
> +      t.string :name
не вижу поля для разделения роли пользователей
у нас две роли: админ и обычный юзер

2021-11-11 14:57 UTC, zakharantoshchenko commented on app/models/field.rb
> +end
подумай как пользователи будут бронировать поля, хватит только этой модели(таблицы)?

2021-11-11 14:57 UTC, zakharantoshchenko commented on .idea/Project.iml
>      <orderEntry type="library" scope="PROVIDED" name="activestorage (v6.1.4.1, rbenv: 3.0.1) [gem]" level="application" />
весь этот файл добавь в .gitignore , погугли как это сделать с уже закомиченым файлом

2021-11-15 11:37 UTC, Nazarii1017 commented on .idea/Project.iml
>      <orderEntry type="library" scope="PROVIDED" name="activestorage (v6.1.4.1, rbenv: 3.0.1) [gem]" level="application" />
updated

2021-11-15 11:37 UTC, Nazarii1017 commented on db/migrate/20211111134104_devise_create_users.rb
> +      t.string :name
done

2021-11-15 13:19 UTC, zakharantoshchenko commented on app/models/booking.rb
> +  has_many :payments
что ты этой связью хочешь сделать?

2021-11-16 17:07 UTC, zakharantoshchenko commented on app/models/booking.rb
> +  belongs_to :schedules
S

2021-11-16 17:20 UTC, zakharantoshchenko approved these changes

2021-11-16 17:23 UTC, merged